### ISSUE TITLE
Implementar botones de agregados de tiempo

### ISSUE THREAD

**Issue by leancontinuo** [mauforonda/dolares#2]
¿Qué te parece esta UI? 

![mock-dolares](https://github.com/user-attachments/assets/607c06de-8fb7-4ebf-a085-abe50d169352)

Por defecto está en `FULL`, esto muestra los datos desde el momento inicial de recolección de datos.

Los demás selectores mostrarán por defecto la última medida de tiempo que se seleccione. Por ejemplo, los últimos tres días.

Luego podemos implementar el slider de manifold que propusiste que se ve re bueno y es compatible con este feature.

**Comment by mauforonda** [comment]
Algunas observaciones rápidas:

- Los botones de tiempo deberían estar debajo y ser visualmente distintos de los de compra/venta. También deberían ser menos visualmente prominentes y quizás con una fuente más pequeña.
- El texto debería ser accesible para usuarios que sólo entienden español y no son familiares con otras series financieras. Una idea sería copiar lo que tengo en [esta otra gráfica](https://observablehq.com/@mauforonda/bloqueos-en-carreteras-de-bolivia).
- La opción seleccionada debería ser inmediatamente reconocible, como "compra" es reconocible en la imagen que compartes. Quizás la vista por defecto debería ser un rango razonablemente largo, digamos 6 meses, pero no la serie completa. 1 hora es muy poco, la opción más corta debería ser quizás 3 días para tener un poco de contexto.

**Comment by leancontinuo** [comment]
1. Simetría
2. Distinción visual inspirada en el ejemplo
3. Accesibilidad de lenguaje (aunque poco accesible para quien le cuesta leer fuentes pequeñas)

Acerca del tercer punto, difiero, la última hora es el contexto. Las cosas pueden cambiar rápidamente, especialmente en tiempos de inflación.

En lo que dudo es el orden, propongo poner el rango más pequeño como última opción. El segmento seleccionado siempre está delimitado a la última observación recolectada; así todo armoniza siempre hacia la derecha.

![dolarinputs](https://github.com/user-attachments/assets/4284a99f-3d08-49ce-a2dd-2fb945488e22)

¿Qué te parece?

**Comment by mauforonda** [comment]
- Los botones de compra / venta deberían estar entre el título y los precios, como en la versión actual. 
- 7 opciones son demasiadas, 3 o 5 es un mejor número. El filtro de 1 hora tendría generalmente 1 sólo punto así que no tiene mucho sentido. En realidad creo que los ticks del eje horizontal estarían medio descuajeringados con menos de una semana. Voto por poner 1 semana, 1 mes y todo. Y luego de un tiempo incluir 3 meses y 6 meses.
- Me gusta lo de invertir el orden de estos botones. Creo.
- El estilo del botón seleccionado debería ser más como el de compra / venta. El verde está reservado para la información que un lector buscaría en los primeros segundos de visita. 

Estaré más de una semana sin acceso a un entorno de desarrollo así que me apresuré en escribir una versión temprana: ce381a6 . 

![image](https://github.com/user-attachments/assets/8c4da018-27cb-44dd-88a4-4a58159a04e2)

Por favor checala y veamos más ideas sobre eso. Gracias mil 🙌.

**Comment by mauforonda** [comment]
Cómo te parece la implementación actual? Crees que podemos cerrar este issue?

**Comment by leancontinuo** [comment]
¡Quedó genial!
